AllCops:
  TargetRubyVersion: 2.4
Style/Documentation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/LineLength:
  Max: 100
Layout/IndentationConsistency:
  EnforcedStyle: rails
  SupportedStyles:
    - rails